#!/usr/bin/env groovy

//ENV Vars
def TOOLS_NAMESPACE = "frjeow-tools"
def DEV_NAMESPACE = "frjeow-dev"
def TEST_NAMESPACE = "frjeow-test"
def PROD_NAMESPACE = "frjeow-prod"

def RABBITMQ = "rabbitmq"
def SEARCH_API = "searchapi"
def SAMPLE_ADAPTER = "sample-adapter"
def ICBC_REST_ADAPTER = "icbc-rest-adapter"
def DYNAMICS_ADAPTER = "dynadapter"
def JAEGER = "jaeger"

def DOMAIN = "pathfinder.gov.bc.ca"
def SUBDOMAIN = "fams3"

def GIT_URI = "https://github.com/bcgov/fams3.git"
def GIT_REF = "master"

def PRIVATE_GIT_URI = "git@github.com:bcgov-c/fams3-openshift.git"
def PRIVATE_GIT_REF = "master"
def PRIVATE_GIT_SECRET = "fams3-github-key"

def BUILD_MEMORY = "1Gi"
def RUN_MEMORY = "512Mi"


def StartBuildAndWait(selector, namespace) {
 echo "Starting build for ${selector} to in ${namespace}..."
 sh "oc start-build ${selector} -n ${namespace} --wait --follow"
 echo "Build complete!"
}

def WaitForDeploy(selector, namespace) {
 echo "Waiting for ${selector} to be deployed in ${namespace}..."
 sh "oc wait dc/${selector} --for=condition=Available --timeout=300s -n ${namespace}"
}

pipeline {
 agent any
 stages {

  stage('Checkout') {
   steps {
    checkout scm
   }
  }

  stage('Build') {
   steps {
    parallel(
     'Search API': {
      echo "Initiating SearchAPI build..."
      sh "oc process -f openshift/templates/search-api.bc.yaml \
         -p NAME=${SEARCH_API} \
         -p SOURCE_REPOSITORY_URL=${GIT_URI} \
         -p SOURCE_REPOSITORY_REF=${GIT_REF} \
         -p DOTNET_STARTUP_PROJECT=app/SearchApi/SearchApi.Web/SearchApi.Web.csproj \
         -p MEMORY_LIMIT=${BUILD_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} | oc apply -f - -n ${TOOLS_NAMESPACE}"
      StartBuildAndWait("${SEARCH_API}-build", TOOLS_NAMESPACE)
      StartBuildAndWait("${SEARCH_API}-runtime", TOOLS_NAMESPACE)
     },
     'Dynamics Adapter': {
      echo "Initiating DynamicsAdapter build..."
      sh "oc process -f openshift/templates/dynamics-adapter.bc.yaml \
         -p NAME=${DYNAMICS_ADAPTER} \
         -p SOURCE_REPOSITORY_URL=${GIT_URI} \
         -p SOURCE_REPOSITORY_REF=${GIT_REF} \
         -p DOTNET_STARTUP_PROJECT=app/DynamicsAdapter/DynamicsAdapter.Web/DynamicsAdapter.Web.csproj \
         -p MEMORY_LIMIT=${BUILD_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} | oc apply -f - -n ${TOOLS_NAMESPACE}"
      StartBuildAndWait("${DYNAMICS_ADAPTER}-build", TOOLS_NAMESPACE)
      StartBuildAndWait("${DYNAMICS_ADAPTER}-runtime", TOOLS_NAMESPACE)
     },
     'Sample Adapter': {
      echo "Initiating SampleAdapter build..."
      sh "oc process -f openshift/templates/sample-adapter.bc.yaml \
         -p NAME=${SAMPLE_ADAPTER} \
         -p SOURCE_REPOSITORY_URL=${GIT_URI} \
         -p SOURCE_REPOSITORY_REF=${GIT_REF} \
         -p DOTNET_STARTUP_PROJECT=app/SearchApi/SearchAdapter.Sample/SearchAdapter.Sample.csproj \
         -p MEMORY_LIMIT=${BUILD_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} | oc apply -f - -n ${TOOLS_NAMESPACE}"
      StartBuildAndWait("${SAMPLE_ADAPTER}-build", TOOLS_NAMESPACE)
      StartBuildAndWait("${SAMPLE_ADAPTER}-runtime", TOOLS_NAMESPACE)
     },
     'ICBC Rest Adapter': {
      echo "Initiating ICBCAdapter build..."
      sh "oc process -f openshift/templates/icbc-adapter.bc.yaml \
         -p NAME=${ICBC_REST_ADAPTER} \
         -p SOURCE_REPOSITORY_URL=${PRIVATE_GIT_URI} \
         -p SOURCE_REPOSITORY_REF=${PRIVATE_GIT_REF} \
         -p SOURCE_SECRET=${PRIVATE_GIT_SECRET} \
         -p DOTNET_STARTUP_PROJECT=src/SearchApi.Adapters/ICBC.Rest.Adapter/ICBC.Rest.Adapter.csproj \
         -p MEMORY_LIMIT=${BUILD_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} | oc apply -f - -n ${TOOLS_NAMESPACE}"
      StartBuildAndWait("${ICBC_REST_ADAPTER}-build", TOOLS_NAMESPACE)
      StartBuildAndWait("${ICBC_REST_ADAPTER}-runtime", TOOLS_NAMESPACE)
     }
    )
   }
  }

  stage('Promote to DEV') {
   steps {
    parallel(
     'Search API': {
      sh "oc process -f openshift/templates/search-api.dc.yaml \
         -p NAME=${SEARCH_API} \
         -p APPLICATION_DOMAIN=${SUBDOMAIN}-dev.${DOMAIN} \
         -p MEMORY_LIMIT=${RUN_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} \
         -p TAG=dev | oc apply -f - -n ${DEV_NAMESPACE}"
      sh "oc tag ${SEARCH_API}:latest ${SEARCH_API}:dev -n ${TOOLS_NAMESPACE}"
      WaitForDeploy(SEARCH_API, DEV_NAMESPACE)
     },
     'Dynamics Adapter': {
      sh "oc process -f openshift/templates/dynamics-adapter.dc.yaml \
         -p NAME=${DYNAMICS_ADAPTER} \
         -p APPLICATION_DOMAIN=${SUBDOMAIN}-dev.${DOMAIN} \
         -p MEMORY_LIMIT=${RUN_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} \
         -p TAG=dev | oc apply -f - -n ${DEV_NAMESPACE}"
      sh "oc tag ${DYNAMICS_ADAPTER}:latest ${DYNAMICS_ADAPTER}:dev -n ${TOOLS_NAMESPACE}"
      WaitForDeploy(DYNAMICS_ADAPTER, DEV_NAMESPACE)
     },
     'Sample Adapter': {
      sh "oc process -f openshift/templates/sample-adapter.dc.yaml \
         -p NAME=${SAMPLE_ADAPTER} \
         -p APPLICATION_DOMAIN=${SUBDOMAIN}-dev.${DOMAIN} \
         -p MEMORY_LIMIT=${RUN_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} \
         -p TAG=dev | oc apply -f - -n ${DEV_NAMESPACE}"
      sh "oc tag ${SAMPLE_ADAPTER}:latest ${SAMPLE_ADAPTER}:dev -n ${TOOLS_NAMESPACE}"
      WaitForDeploy(SAMPLE_ADAPTER, DEV_NAMESPACE)
     },
     'ICBC Rest Adapter': {
      sh "oc process -f openshift/templates/icbc-adapter.dc.yaml \
         -p NAME=${ICBC_REST_ADAPTER} \
         -p APPLICATION_DOMAIN=${SUBDOMAIN}-dev.${DOMAIN} \
         -p MEMORY_LIMIT=${RUN_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} \
         -p TAG=dev | oc apply -f - -n ${DEV_NAMESPACE}"
      sh "oc tag ${ICBC_REST_ADAPTER}:latest ${ICBC_REST_ADAPTER}:dev -n ${TOOLS_NAMESPACE}"
      WaitForDeploy(ICBC_REST_ADAPTER, DEV_NAMESPACE)
     }
    )
   }
  }

  stage('Promote to TEST') {
   steps {
    parallel(
     'Search API': {
      sh "oc process -f openshift/templates/search-api.dc.yaml \
         -p NAME=${SEARCH_API} \
         -p APPLICATION_DOMAIN=${SUBDOMAIN}-test.${DOMAIN} \
         -p MEMORY_LIMIT=${RUN_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} \
         -p TAG=test | oc apply -f - -n ${TEST_NAMESPACE}"
      sh "oc tag ${SEARCH_API}:dev ${SEARCH_API}:test -n ${TOOLS_NAMESPACE}"
      WaitForDeploy(SEARCH_API, TEST_NAMESPACE)
     },
     'Dynamics Adapter': {
      sh "oc process -f openshift/templates/dynamics-adapter.dc.yaml \
         -p NAME=${DYNAMICS_ADAPTER} \
         -p APPLICATION_DOMAIN=${SUBDOMAIN}-test.${DOMAIN} \
         -p MEMORY_LIMIT=${RUN_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} \
         -p TAG=test | oc apply -f - -n ${TEST_NAMESPACE}"
      sh "oc tag ${DYNAMICS_ADAPTER}:dev ${DYNAMICS_ADAPTER}:test -n ${TOOLS_NAMESPACE}"
      WaitForDeploy(DYNAMICS_ADAPTER, TEST_NAMESPACE)
     },
     'Sample Adapter': {
      sh "oc process -f openshift/templates/sample-adapter.dc.yaml \
         -p NAME=${SAMPLE_ADAPTER} \
         -p APPLICATION_DOMAIN=${SUBDOMAIN}-test.${DOMAIN} \
         -p MEMORY_LIMIT=${RUN_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} \
         -p TAG=test | oc apply -f - -n ${TEST_NAMESPACE}"
      sh "oc tag ${SAMPLE_ADAPTER}:dev ${SAMPLE_ADAPTER}:test -n ${TOOLS_NAMESPACE}"
      WaitForDeploy(SAMPLE_ADAPTER, TEST_NAMESPACE)
     },
     'ICBC Rest Adapter': {
      sh "oc process -f openshift/templates/icbc-adapter.dc.yaml \
         -p NAME=${ICBC_REST_ADAPTER} \
         -p APPLICATION_DOMAIN=${SUBDOMAIN}-test.${DOMAIN} \
         -p MEMORY_LIMIT=${RUN_MEMORY} \
         -p NAMESPACE=${TOOLS_NAMESPACE} \
         -p TAG=test | oc apply -f - -n ${TEST_NAMESPACE}"
      sh "oc tag ${ICBC_REST_ADAPTER}:dev ${ICBC_REST_ADAPTER}:test -n ${TOOLS_NAMESPACE}"
      WaitForDeploy(ICBC_REST_ADAPTER, TEST_NAMESPACE)
     }
    )
   }
  } 
 }
}