# Add 'Search Api' to changes in search api
'Search Api':
- changed-files:
  - any-glob-to-any-file: 'app/SearchApi/**/*'

# Add 'Dynamics Adapter' to changes in dynamics adapter
'Dynamics Adapter':
- changed-files:
  - any-glob-to-any-file: 'app/DynamicsAdapter/**/*'

# Add 'DevOps' to changes in openshift folder
'DevOps':
- changed-files:
  - any-glob-to-any-file: 'openshift/**/*'

# Add 'Splunk' to changes in splunk folder
'Splunk':
- changed-files:
  - any-glob-to-any-file: 'splunk/**/*'
