apiVersion: v1
kind: Template
labels:
  template: image-stream-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: image stream template
    description: |-
      This is a template for web-adapter image stream.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: imagestream-template
parameters:
  - description: The OpenShift Namespace prefix.
    displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
    name: namespacePrefix
    required: true
    value:
  - description: The name assigned to all of the frontend objects defined in this template.
    displayName: Name
    name: appName
    required: true
    value:
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    labels:
      application: ${appName}
    name: ${appName}
    namespace: ${namespacePrefix}-tools